version: '3.0'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    networks:
      webnet:
        ipv4_address: 10.0.15.2

networks:
  webnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.15.0/29